myTuple = (1, 4, 3, 2, 5)
myTuple1 = (1, 2, 6, 9, 8, 7)
print(myTuple + myTuple1)
print(myTuple * 4)
print(4 in myTuple)
print(myTuple.count(2))
print(myTuple.index(5))
print(len(myTuple))
print(max(myTuple1))
print(min(myTuple1))
print(tuple([1, 4, 6, 7]))

